version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron-log
    versions:
    - 4.3.1
  - dependency-name: "@types/react-select"
    versions:
    - 3.0.26
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@types/jqueryui"
    versions:
    - 1.12.13
